# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节名')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('pic', models.ImageField(default='course/python面向对象.jpg', upload_to='course/%Y/%m/', verbose_name='封面')),
                ('time', models.IntegerField(help_text='以分钟计', verbose_name='时长')),
                ('desc', models.CharField(max_length=100, verbose_name='课程简介')),
                ('introduce', models.TextField(verbose_name='课程详情')),
                ('level', models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, verbose_name='课程难度')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('collection_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('study_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程类别')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程类别',
                'verbose_name_plural': '课程类别',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='资源名称')),
                ('download', models.FileField(upload_to='resources/%Y/%m', verbose_name='资源地址')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='视频名')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseTab', verbose_name='课程类别'),
        ),
    ]
