# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 15:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180108_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tips1',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='tips2',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='可以学到什么'),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduce',
            field=ckeditor.fields.RichTextField(default='', verbose_name='课程详情'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pic',
            field=models.ImageField(default='course/python面向对象.jpg', upload_to='course/%Y/%m', verbose_name='封面'),
        ),
    ]
