# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180117_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='introduce',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='课程详情'),
        ),
    ]
