# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180117_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_num',
            new_name='click',
        ),
    ]
