# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(default='user_head_pic/default_middile_2.png', upload_to='user_head_pic/%Y/%m', verbose_name='头像'),
        ),
    ]
