# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 09:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['click'], 'verbose_name': '讲师信息', 'verbose_name_plural': '讲师信息'},
        ),
        migrations.RenameField(
            model_name='org',
            old_name='collection',
            new_name='collection_num',
        ),
        migrations.AlterField(
            model_name='org',
            name='introduce',
            field=ckeditor.fields.RichTextField(default='', verbose_name='机构介绍'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='teacher/default_middile_2_WZ1559E.png', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
