# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20180117_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='introduce',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='机构介绍'),
        ),
    ]
