# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercollection',
            name='school',
        ),
        migrations.RemoveField(
            model_name='usercollection',
            name='teacher',
        ),
        migrations.AddField(
            model_name='usercollection',
            name='collet_id',
            field=models.IntegerField(default=3, verbose_name='收藏id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercollection',
            name='type',
            field=models.IntegerField(choices=[(1, '机构'), (2, '讲师'), (3, '课程')], default=3, verbose_name='收藏类别'),
        ),
    ]
