# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180110_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={'ordering': ['-add_time'], 'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
