# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20180120_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
