# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20171124_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicmessage',
            name='send_user',
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='recv_user',
            field=models.IntegerField(default=0, verbose_name='收件人'),
        ),
    ]
